title: "Disciplinas - Matemática"
description: "Cálculo | Cálculo Numérico Avançado | Faculdade de Ciências e Tecnologia (FCT) | Universidade Estadual Paulista 'Júlio de Mesquita Filho'"
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#A5D6A7"          # Verde escuro (início do cabeçalho)
  gradient_left: "#ff69b4"   # Roxo médio
  gradient_right: "#8E24AA"  # Roxo mais claro
logo_url: https://posmac-fct.github.io/assets/images/mario.png
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: View Documentation
  zip_hide: false
  tar_hide: true
  github_hide: true




